spring.application.name=loginregister
server.port=8000

spring.cloud.nacos.server-addr=127.0.0.1:8848
spring.config.import=nacos:service-user.properties

spring.datasource.url=jdbc:mysql://localhost:3306/yuqing?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath*:mapper/*.xml
